import { draftTitle } from './llm-prompt.js';
import type { LlmGenerateParams, LlmProvider, LlmResult } from './llm.types.js';

/**
 * Deterministic fallback provider. Used when no LLM_PROVIDER (or no API key)
 * is configured, so local development and CI remain reproducible and offline.
 * Produces the same bookend format the original mockLLMCall() emitted.
 */
export class MockLlmProvider implements LlmProvider {
  readonly name = 'mock' as const;

  async generate(params: LlmGenerateParams): Promise<LlmResult> {
    const skill = params.skillSpecialization ?? 'General AI Assistant';
    return {
      title: draftTitle(params.skillSpecialization, params.contentTitle),
      body: [
        '## AI-Generated Response',
        '',
        `**Skill:** ${skill}`,
        `**Prompt:** ${params.prompt}`,
        '',
        'This is a mock LLM response (no provider configured).',
        '',
        '---',
        '',
        `*Generated by ${skill} at ${new Date().toISOString()}*`,
      ].join('\n'),
    };
  }
}
